version: "3.1"
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pw
#  web:
#    depends_on:
#      - db
#    build: .
#    ports:
#      - "3000:3000"
#    restart: always
#    environment:
#      DB_HOST: db:3306
#      DB_USER: admin
#      DB_PASSWORD: pw
volumes:
    db_data:
